---
title: "portfolio"
description: |
  Kulbir's journey to learning and mastering R !!
  Find the code for the visualizations on my social media pages & github 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggbump)
library(lubridate)
library(ggforce)
library(flexdashboard)
library(medicaldata)
library(tidyverse)
library(reactable)
library(crosstalk)
library(plotly)
library(htmltools)
library(skimr)
```

# Which cities have the best parks

```{r echo=FALSE, warning=FALSE, results="hide"}
parks <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-22/parks.csv')

glimpse(parks)

# EDA trying to remove the % sign from the park_pct_city_data using parse_number used Kiesei stream 

parks_df <- parks %>% 
  mutate(park_pct_city_data = parse_number(park_pct_city_data),
         pct_near_park_data = parse_number(pct_near_park_data),
         spend_per_resident_data = parse_number(spend_per_resident_data)) %>% 
  mutate(across(where(is.character), factor)) %>% 
  select(-city_dup)

parks_df

unique(parks_df$city)

# Recoding for the 2 different Washington DC spellings 
parks_recode <- parks_df %>%  
  mutate(city = recode(city, 
                       "Washington, D.C." = "Washington, DC"))

top_parks <- c("Minneapolis", "Washington, DC", "St. Paul", "Arlington, Virginia", "Cincinnati", "Portland", "Irvine", "San Francisco", "Boston", "Chicago")

top <- parks_recode %>% 
  filter(city %in% top_parks)
 
plot <- top %>%  
  ggplot(aes(year, rank, color = city)) +
  geom_point(size = 2) +
  geom_bump() +
  theme(plot.background = element_blank())+
  scale_y_reverse() +
  theme(panel.background = element_rect(fill = "black", color = "green"),
        panel.grid = element_blank()) +
  scale_x_continuous( limits = c(2012, 2022),
                      breaks = seq( 2012, 2020, 
                                    by = 2)) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  geom_text(data = top %>%
              filter(year == max(year)),
            aes(x = year + 0.2, label = city),
            size = 3, hjust = 0) +
  labs(title ="Top 10 park cities of 2020 & their ranks through the years",
       caption = "Source: TidyTuesday |inspired by: @kierisi")

plot
```

# Happy Birthday to the Lemurs 

```{r echo=FALSE, warning=FALSE, results="hide"}
lemurs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-24/lemur_data.csv')

unique(lemurs$birth_institution)

lemurs %>% filter(birth_institution == "NMADAGASCAR" | birth_institution == "Madagascar / North /" | birth_institution == "Madagascar /" ) %>% unique() %>% group_by(dob, birth_institution) %>% count() %>% view()

my_birthyear <- lemurs %>% 
  group_by(dlc_id) %>% 
  mutate(dob = min(ymd(dob))) %>% 
  mutate(year_joined = year(dob)) %>% 
  mutate(birth_institution = recode (birth_institution, "Madagascar / North /" = "Madagascar")) %>% 
  mutate(birth_institution = recode(birth_institution, "Madagascar /" = "Madagascar")) %>% 
  mutate(birth_institution = recode(birth_institution, "NMADAGASCAR" = "Madagascar")) %>% 
  filter(birth_institution == "Madagascar" | birth_institution == "Duke Lemur Center") %>% 
  mutate() %>% 
  mutate(Month = lubridate::month(birth_month, label = TRUE, abbr = FALSE)) %>%
  summarise(name, taxon, year_joined, birth_institution, Month) %>% 
  unique() %>% 
  group_by(year_joined, birth_institution) %>% 
  mutate( n = length(year_joined)) %>% 
  unique()

my_birthyear$birth_institution <- factor(my_birthyear$birth_institution, levels = c("Duke Lemur Center", "Madagascar"))

lemur_birthday <-ggplot(my_birthyear, aes(x = year_joined, fill = birth_institution), color = white) + geom_area(stat = "bin") + scale_fill_brewer(palette = "Greens") +
  theme_classic() +
  theme(axis.line = element_line(color = 'white', size = 0.05))+
  theme(legend.position = "bottom", legend.title = element_blank(), legend.background = element_rect(fill = "#A78B74" )) +
  labs(title = "What happened to Lemurs in Madagascar?", x = "Birth Year", y = "count", subtitle = "No data available for Madagascar after 1990", caption = "Data:#tidytuesday | twitter:@shldbcrzy | inspired by:@alyssastweeting") +
  theme(plot.title = element_text(size = 14)) +
  theme(axis.title = element_text(size = 6, face = "bold")) +
  theme(axis.line = element_line(color = "#A78B74", size = 0.05)) +
  theme(axis.ticks.y = element_blank(), axis.ticks.x = element_blank()) +
  theme(panel.background = element_rect(fill = "#A78B74")) +
  theme(plot.background = element_rect(fill = "#A78B74")) +
  facet_zoom(x = birth_institution == "Madagascar", ylim = c(0, 20), horizontal = FALSE, show.area = FALSE)

lemur_birthday
```

# Best city for female PhD's 

```{r echo=FALSE, warning=FALSE, results="hide"}
# Circular plot
#ask a manager data 
tuesdata <- tidytuesdayR::tt_load(2021, week = 21)
survey <- tuesdata$survey

phd_survey <- survey %>% 
  filter(highest_level_of_education_completed %in% "PhD") %>% 
  filter(currency == "USD" & country %in% c("United States", "USA", "US", "U.S.", "United States of America", "Usa", "United states", "united states", "Us")) %>% 
  mutate(gender = fct_collapse(gender,"Other/prefer not to answer" = c("Other or prefer not to answer", "Prefer not to answer", "Non-binary")), gender = fct_relevel(gender, "Woman")) %>% mutate(state = recode(state, "California, Oregon" = "California")) %>% 
  mutate(state = recode(state, "Montana, Wyoming" = "Montana")) %>% 
  mutate(state = recode(state, "Indiana, Ohio" = "Indiana"))

plot_1 <- phd_survey %>% 
  drop_na(gender, state) %>% 
  filter(gender == "Woman") %>% 
  group_by(state) %>%
  summarise(avg_salary = mean(annual_salary)) %>% 
  arrange(avg_salary) %>% 
  mutate(id = row_number())

# https://bjnnowak.netlify.app/2021/08/31/r-polar-barplots/ 
# https://www.r-graph-gallery.com/296-add-labels-to-circular-barplot.html
(fig <- plot_1 %>% 
    ggplot(aes(x = id, y = avg_salary)) +
    geom_bar(stat = "identity", fill = "#FF3368")  +
    ylim(0,150000)+
    theme_minimal() +
    theme(panel.background = element_rect(fill = "pink", color = "pink"),
          axis.text = element_blank(),
          axis.title = element_blank(),
          panel.grid = element_blank(),
          plot.background = element_rect(fill = "pink", color = "pink"),
          plot.margin = margin(t=0.5, r=0.5, b=0.5,l=0.5, unit = "cm")) +
    coord_polar(start = 0))

plot_labeled <- plot_1 %>% 
  mutate(angle = 90-306*(id-0.5)/max(id))

fig + geom_text(
  data = plot_labeled, 
  aes(x = id, y = avg_salary, label = state, angle = angle), 
  hjust = 0
)

plot_labeled <- plot_labeled %>% 
  mutate(hjust = case_when(angle <=-90~1, TRUE~0)) %>% 
  mutate(angle = case_when(angle<=-90~angle+180,TRUE~angle))
  
fig <- fig + geom_text(
  data = plot_labeled, 
  aes(x = id, y = avg_salary +10 , label = state, angle = angle, hjust = hjust), size = 1.5, color = "purple"
) +
  labs(title = "Where should I move next?", caption = "Source: #tidytuesday |inspired by: @BjnNowak")

fig

```



